version: '3.8'

services:
  fincheck_database:
    container_name: fincheck-database
    image: postgres:alpine
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - 'fincheck_database:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fincheck
  fincheck_adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'

volumes:
  fincheck_database: